# GitHub Actions workflow for govulncheck.
# This file is licensed under MIT License.
# Copied from https://github.com/fxamacker/cbor

name: govulncheck

# Revoke default permissions and grant what's needed in each job.
permissions: {}

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**'
      - '!**.md'
  push:
    paths:
      - '**'
      - '!**.md'
    branches:
      - 'main'
      - 'master'
      - 'release*'
      - 'feature/stream-mode'
    tags:
      - 'v*'

jobs:
  Check:
    runs-on: ubuntu-latest
    permissions:
      # Grant permission to read content.
      contents: read
    steps:
    - name: Checkout source
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: 1
    - name: Set up Go
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
      with:
        go-version: 1.21.x
        check-latest: true
    - name: Install latest from golang.org
      run: go install golang.org/x/vuln/cmd/govulncheck@5507063454b1b8c930db99818a88b52f1f143418 # v1.0.4
    - name: Run govulncheck      
      run: govulncheck -show=traces ./...
